# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: refresh_token.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'refresh_token.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13refresh_token.proto\x12\x04\x61uth\",\n\x13RefreshTokenRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\"h\n\x11RefreshTokenReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x02 \x01(\t\x12\x15\n\rrefresh_token\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t2Q\n\x0b\x41uthService\x12\x42\n\x0cRefreshToken\x12\x19.auth.RefreshTokenRequest\x1a\x17.auth.RefreshTokenReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'refresh_token_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REFRESHTOKENREQUEST']._serialized_start=29
  _globals['_REFRESHTOKENREQUEST']._serialized_end=73
  _globals['_REFRESHTOKENREPLY']._serialized_start=75
  _globals['_REFRESHTOKENREPLY']._serialized_end=179
  _globals['_AUTHSERVICE']._serialized_start=181
  _globals['_AUTHSERVICE']._serialized_end=262
# @@protoc_insertion_point(module_scope)
